import type {
  AnalysisResult,
  GeneratedReport,
  VerificationNote,
} from "./types";

export function verifyFindings(
  findings: Array<{ id: string; quote: string }>,
): VerificationNote[] {
  return findings.map((finding) => ({
    findingId: finding.id,
    supported: finding.quote.trim().length > 0,
    reason: finding.quote.trim()
      ? "Mock verification: finding is backed by a stored quote."
      : "Mock verification: finding has no supporting quote.",
  }));
}

export function analyseFindings(
  question: string,
  findings: Array<{ subject: string; attribute: string; value: string }>,
): AnalysisResult {
  const summary =
    findings.length > 0
      ? `Mock analysis of "${question}": ${findings
          .map((finding) => `${finding.subject} ${finding.attribute} is ${finding.value}`)
          .join("; ")}.`
      : `Mock analysis of "${question}": no findings were extracted.`;

  return {
    summary,
    conflicts: [],
  };
}

export function generateReport(input: {
  question: string;
  analysis: AnalysisResult;
  findings: Array<{
    subject: string;
    attribute: string;
    value: string;
    quote: string;
    sourceId: string;
  }>;
  sources: Array<{ id: string; title: string; url: string }>;
}): GeneratedReport {
  const findingLines = input.findings.map(
    (finding) =>
      `- **${finding.subject} / ${finding.attribute}:** ${finding.value} (source ${finding.sourceId})`,
  );
  const sourceLines = input.sources.map(
    (source, index) => `${index + 1}. [${source.title}](${source.url})`,
  );

  const markdown = [
    `# Research report`,
    ``,
    `**Question:** ${input.question}`,
    ``,
    `## Summary`,
    input.analysis.summary,
    ``,
    `## Findings`,
    findingLines.join("\n") || "_No findings._",
    ``,
    `## Sources`,
    sourceLines.join("\n") || "_No sources._",
    ``,
    `_This report was generated by the Phase 2C pipeline. Verification, analysis, and report generation remain mocked._`,
  ].join("\n");

  return {
    markdown,
    outline: {
      sections: ["Summary", "Findings", "Sources"],
    },
  };
}
